<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <link href="/css/styles.css" rel="stylesheet">
        <link href="/css/signin.css" rel="stylesheet">
    </head>
    <body class="text-center">
        <form class="form-signin" method="POST">
            <h1 class="h3 mb-3 font-weight-normal">
                <?php if ($err): ?>
                    Try again
                <?php else: ?>
                    Please sign in
                <?php endif ?>
            </h1>
        
            <label for="inputLogin" class="sr-only">Login</label>
            <input type="text" name="login" id="inputLogin" class="form-control" placeholder="Login" required autofocus>
        
            <label for="inputPassword" class="sr-only">Password</label>
            <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>
        
            <div class="checkbox mb-3">
                <label>
                    <input type="checkbox" value="remember-me"> Remember me
                </label>
            </div>
            
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        </form>
    </body>
</html>
