<!DOCTYPE html>
<html>
    <head>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/autogrow@1.0.6/autogrow.min.js"></script>
        <script src="js/main.js"></script>
    </head>
    <body>
        <div class="container">
            <h1>Domain Info</h1>
            <hr />
            <div id="GetDomainsInfo">
                <input type="hidden" name="action" value="GetStatus" />
                <div class="form-group">
                    <input id="ExcludeActive" name="ExcludeActive" type="checkbox" checked />
                    <label for="ExcludeActive">Exclude active</label>
                </div>
                <div class="form-group">
                    <textarea id="Domains" name="Domains" class="form-control" type="text"></textarea>
                </div>
                <input type="button" class="btn btn-primary" value="Submit" />
                <div id="Loading" style="visibility: hidden; " class="spinner-border spinner-border-sm ml-3"></div>
            </div>
            <hr />
            <div id="AjaxContent"></div>
        </div>
    </body>
</html>
